## Interpretting Differentially Expressed Genes (DEGs) in RNA-Seq Data

### Introduction to Tools and File Formats

Before we begin, let's review the tools and file formats used in this tutorial.

#### AGAT (A General Annotation Tool)
**AGAT** is a toolkit for the manipulation of genome annotations. It is often used to work with GFF files, which are a standard format for storing gene and transcript annotations. One of the key features of AGAT is its ability to filter and process these GFF files, such as extracting the longest isoform of each transcript.

#### Mercator
**Mercator** is a web server designed for functional annotation of genes. It takes protein sequences (in FASTA format) as input and assigns functional categories to them based on sequence similarity to known proteins.

#### GFF File
A **GFF (General Feature Format)** file contains information about the positions and attributes of genes, transcripts, and other features in a genome. Here's an example of what a GFF file looks like:

```
##gff-version 3
chr1    source  gene    1000    5000    .   +   .   ID=gene1;Name=Gene1
chr1    source  mRNA    1000    5000    .   +   .   ID=mRNA1;Parent=gene1
chr1    source  exon    1000    2000    .   +   .   ID=exon1;Parent=mRNA1
chr1    source  exon    3000    4000    .   +   .   ID=exon2;Parent=mRNA1
```

#### Protein FASTA File
A **Protein FASTA file** contains sequences of proteins in the FASTA format. Each sequence starts with a header line, followed by the protein sequence itself. Here's an example:

```
>protein1
MKTIIALSYIFCLVFADYKDDDDK
>protein2
MVLSPADKTNVKAAWGSISAFAGVR
```

---

## Step 1: Downloading the GFF and FASTA Files

Before running AGAT, you'll need the genome and annotation files for the organism you're studying. These files should be downloaded and unzipped as shown below, if not done before.

In [ ]:
%%bash
set -euo pipefail

GENOME="/mnt/volume/data/group8/studies/rice/references/osa1_r7.asm.fa"
ANNOT="/mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.gff3"

# ----------------------------
# Genome
# ----------------------------
if [ ! -f "${GENOME}" ]; then
    wget -q -c -O ${GENOME}.gz https://rice.uga.edu/osa1r7_download/osa1_r7.asm.fa.gz 
    unpigz "${GENOME}.gz"
else
    echo "Genome already exists — skipping."
fi

# ----------------------------
# Annotation
# ----------------------------
if [ ! -f "${ANNOT}" ]; then
    wget -q -c -O ${ANNOT}.gz https://rice.uga.edu/osa1r7_download/osa1_r7.all_models.gff3.gz
    unpigz "${ANNOT}.gz"
else
    echo "Annotation already exists — skipping."
fi

Genome already exists — skipping.
Annotation already exists — skipping.


Explanation:
- The genome in FASTA format (`.fa.gz`) and the annotation in GFF3 format (`.gff3.gz`) are downloaded for *Triticum aestivum* (wheat).
- The `unpigz` command is used to unzip the downloaded files.

---

## Step 2: Running AGAT to Keep the Longest Isoform
Now that you have the GFF file, you can run AGAT to keep the longest isoform of each transcript. This is useful when you want to work with a simplified version of your annotation, focusing on the longest transcript for each gene.

> **Warning**  
> agat did not play along well with Jupyter, open a terminal and run these commands inside of tmux.

In [ ]:
%%bash
agat_sp_keep_longest_isoform.pl \
  -f /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.gff3 \
  -o /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.longest_transcript.gff3

 ------------------------------------------------------------------------------
|   Another GFF Analysis Toolkit (AGAT) - Version: v1.7.0                      |
|   https://github.com/NBISweden/AGAT                                          |
|   National Bioinformatics Infrastructure Sweden (NBIS) - www.nbis.se         |
 ------------------------------------------------------------------------------
Using standard /mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/auto/share/dist/AGAT/feature_levels.yaml file
=> Output format will be GFF3.


                          ------ Start parsing ------
-------------------------- parse options and metadata --------------------------
Accessing the feature_levels YAML file
=> Attribute used to group features when no Parent/ID relationship exists (i.e common tag):
	* locus_tag
	* gene_id
=> merge_loci option activated
=> FASTA within the file will be thrown away!
=> Machine information:
	This script is being run by perl v5.32.1
	Bioperl location being used: /mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/Bio/
	Operating system being used: linux
=> Accessing Ontology
	No ontology accessible from the gff file header!
	We use the SOFA ontology distributed with AGAT:
		/mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo
	Read ontology /mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo:
		4 root terms, and 2596 total terms, and 1516 leaf terms
	Filtering ontology:
		We found 1861 terms that are sequence_feature or is_a child of it.
--------------------- collecting general data information ----------------------
Parsing file /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.gff3
=> Number of line in file: 813791
=> Number of comment lines: 1
=> Number of empty lines: 2
=> Fasta included: No
=> Number of features lines: 813788
=> Number of feature lines with 1 fields (while 9 expected): 1
=> Number of feature type (3rd column): 6
	* Level1: 1 => gene
	* level2: 1 => mRNA
	* level3: 4 => CDS exon five_prime_UTR three_prime_UTR
	* unknown: 0 =>
=> Version of the GFF parser selected by AGAT: 3

-------- Start of in-depth analysis (file by chunck 1 CPU - 7 chuncks) ---------

[Tue Apr 28 08:42:37 2026] Parsing:   0%
[Tue Apr 28 08:42:38 2026] Parsing:   0%
[Tue Apr 28 08:42:38 2026] Parsing:   0%
[Tue Apr 28 08:42:39 2026] Parsing:   1%
[Tue Apr 28 08:42:39 2026] Parsing:   2%
[Tue Apr 28 08:42:40 2026] Parsing:   2%
[Tue Apr 28 08:42:40 2026] Parsing:   3%
[Tue Apr 28 08:42:41 2026] Parsing:   4%
[Tue Apr 28 08:42:41 2026] Parsing:   4%
[Tue Apr 28 08:42:42 2026] Parsing:   5%
[Tue Apr 28 08:42:42 2026] Parsing:   6%
[Tue Apr 28 08:42:43 2026] Parsing:   6%
[Tue Apr 28 08:42:43 2026] Parsing:   7%
[Tue Apr 28 08:42:44 2026] Parsing:   8%
[Tue Apr 28 08:42:44 2026] Parsing:   8%
[Tue Apr 28 08:42:45 2026] Parsing:   9%
[Tue Apr 28 08:42:45 2026] Parsing:  10%
[Tue Apr 28 08:42:46 2026] Parsing:  10%
[Tue Apr 28 08:42:46 2026] Parsing:  11%
[Tue Apr 28 08:42:47 2026] Parsing:  12%
[Tue Apr 28 08:42:47 2026] Parsing:  13%
[Tue Apr 28 08:42:48 2026] Parsing:  13%
[Tue Apr 28 08:42:48 2026] Parsing:  14%
[Tue Apr 28 08:42:49 2026] Parsing:  15%
[Tue Apr 28 08:42:49 2026] Parsing:  15%
[Tue Apr 28 08:42:55 2026] Parsing:  15%
[Tue Apr 28 08:42:56 2026] Parsing:  16%
[Tue Apr 28 08:42:56 2026] Parsing:  17%
[Tue Apr 28 08:42:57 2026] Parsing:  17%
[Tue Apr 28 08:42:57 2026] Parsing:  18%
[Tue Apr 28 08:42:58 2026] Parsing:  19%
[Tue Apr 28 08:42:58 2026] Parsing:  19%
[Tue Apr 28 08:42:59 2026] Parsing:  20%
[Tue Apr 28 08:42:59 2026] Parsing:  21%
[Tue Apr 28 08:43:00 2026] Parsing:  21%
[Tue Apr 28 08:43:00 2026] Parsing:  22%
[Tue Apr 28 08:43:01 2026] Parsing:  23%
[Tue Apr 28 08:43:01 2026] Parsing:  23%
[Tue Apr 28 08:43:02 2026] Parsing:  24%
[Tue Apr 28 08:43:02 2026] Parsing:  25%
[Tue Apr 28 08:43:03 2026] Parsing:  26%
[Tue Apr 28 08:43:03 2026] Parsing:  26%
[Tue Apr 28 08:43:04 2026] Parsing:  27%
[Tue Apr 28 08:43:04 2026] Parsing:  28%
[Tue Apr 28 08:43:05 2026] Parsing:  28%
[Tue Apr 28 08:43:05 2026] Parsing:  29%
[Tue Apr 28 08:43:06 2026] Parsing:  30%
[Tue Apr 28 08:43:06 2026] Parsing:  30%
[Tue Apr 28 08:43:07 2026] Parsing:  31%
[Tue Apr 28 08:43:07 2026] Parsing:  32%
[Tue Apr 28 08:43:08 2026] Parsing:  32%
[Tue Apr 28 08:43:08 2026] Parsing:  33%
[Tue Apr 28 08:43:09 2026] Parsing:  34%
[Tue Apr 28 08:43:09 2026] Parsing:  34%
[Tue Apr 28 08:43:16 2026] Parsing:  34%
[Tue Apr 28 08:43:17 2026] Parsing:  35%
[Tue Apr 28 08:43:17 2026] Parsing:  36%
[Tue Apr 28 08:43:18 2026] Parsing:  36%
[Tue Apr 28 08:43:18 2026] Parsing:  37%
[Tue Apr 28 08:43:19 2026] Parsing:  37%
[Tue Apr 28 08:43:19 2026] Parsing:  38%
[Tue Apr 28 08:43:20 2026] Parsing:  39%
[Tue Apr 28 08:43:20 2026] Parsing:  40%
[Tue Apr 28 08:43:21 2026] Parsing:  40%
[Tue Apr 28 08:43:21 2026] Parsing:  41%
[Tue Apr 28 08:43:22 2026] Parsing:  42%
[Tue Apr 28 08:43:22 2026] Parsing:  42%
[Tue Apr 28 08:43:23 2026] Parsing:  43%
[Tue Apr 28 08:43:23 2026] Parsing:  44%
[Tue Apr 28 08:43:24 2026] Parsing:  44%
[Tue Apr 28 08:43:24 2026] Parsing:  45%
[Tue Apr 28 08:43:25 2026] Parsing:  46%
[Tue Apr 28 08:43:25 2026] Parsing:  46%
[Tue Apr 28 08:43:26 2026] Parsing:  47%
[Tue Apr 28 08:43:30 2026] Parsing:  47%
[Tue Apr 28 08:43:31 2026] Parsing:  48%
[Tue Apr 28 08:43:31 2026] Parsing:  48%
[Tue Apr 28 08:43:32 2026] Parsing:  49%
[Tue Apr 28 08:43:32 2026] Parsing:  50%
[Tue Apr 28 08:43:33 2026] Parsing:  50%
[Tue Apr 28 08:43:33 2026] Parsing:  51%
[Tue Apr 28 08:43:34 2026] Parsing:  52%
[Tue Apr 28 08:43:34 2026] Parsing:  52%
[Tue Apr 28 08:43:35 2026] Parsing:  53%
[Tue Apr 28 08:43:35 2026] Parsing:  54%
[Tue Apr 28 08:43:36 2026] Parsing:  54%
[Tue Apr 28 08:43:36 2026] Parsing:  55%
[Tue Apr 28 08:43:37 2026] Parsing:  56%
[Tue Apr 28 08:43:37 2026] Parsing:  56%
[Tue Apr 28 08:43:38 2026] Parsing:  57%
[Tue Apr 28 08:43:38 2026] Parsing:  58%
[Tue Apr 28 08:43:39 2026] Parsing:  58%
[Tue Apr 28 08:43:39 2026] Parsing:  59%
[Tue Apr 28 08:43:40 2026] Parsing:  59%
[Tue Apr 28 08:43:40 2026] Parsing:  60%
[Tue Apr 28 08:43:41 2026] Parsing:  61%
[Tue Apr 28 08:43:41 2026] Parsing:  62%
[Tue Apr 28 08:43:42 2026] Parsing:  62%
[Tue Apr 28 08:43:42 2026] Parsing:  63%
[Tue Apr 28 08:43:43 2026] Parsing:  64%
[Tue Apr 28 08:43:43 2026] Parsing:  64%
[Tue Apr 28 08:43:44 2026] Parsing:  65%
[Tue Apr 28 08:43:44 2026] Parsing:  66%
[Tue Apr 28 08:43:45 2026] Parsing:  66%
[Tue Apr 28 08:43:45 2026] Parsing:  67%
[Tue Apr 28 08:43:46 2026] Parsing:  68%
[Tue Apr 28 08:43:46 2026] Parsing:  68%
[Tue Apr 28 08:43:47 2026] Parsing:  69%
[Tue Apr 28 08:43:56 2026] Parsing:  69%
[Tue Apr 28 08:43:56 2026] Parsing:  70%
[Tue Apr 28 08:43:57 2026] Parsing:  71%
[Tue Apr 28 08:43:57 2026] Parsing:  71%
[Tue Apr 28 08:43:58 2026] Parsing:  72%
[Tue Apr 28 08:43:58 2026] Parsing:  73%
[Tue Apr 28 08:43:59 2026] Parsing:  73%
[Tue Apr 28 08:43:59 2026] Parsing:  74%
[Tue Apr 28 08:44:00 2026] Parsing:  75%
[Tue Apr 28 08:44:00 2026] Parsing:  75%
[Tue Apr 28 08:44:01 2026] Parsing:  76%
[Tue Apr 28 08:44:01 2026] Parsing:  77%
[Tue Apr 28 08:44:02 2026] Parsing:  78%
[Tue Apr 28 08:44:02 2026] Parsing:  78%
[Tue Apr 28 08:44:03 2026] Parsing:  79%
[Tue Apr 28 08:44:03 2026] Parsing:  79%
[Tue Apr 28 08:44:04 2026] Parsing:  80%
[Tue Apr 28 08:44:04 2026] Parsing:  81%
[Tue Apr 28 08:44:05 2026] Parsing:  82%
[Tue Apr 28 08:44:05 2026] Parsing:  82%
[Tue Apr 28 08:44:06 2026] Parsing:  83%
[Tue Apr 28 08:44:06 2026] Parsing:  84%
[Tue Apr 28 08:44:07 2026] Parsing:  84%
[Tue Apr 28 08:44:07 2026] Parsing:  85%
[Tue Apr 28 08:44:08 2026] Parsing:  86%
[Tue Apr 28 08:44:08 2026] Parsing:  86%
[Tue Apr 28 08:44:15 2026] Parsing:  86%
[Tue Apr 28 08:44:15 2026] Parsing:  87%
[Tue Apr 28 08:44:16 2026] Parsing:  88%
[Tue Apr 28 08:44:16 2026] Parsing:  88%
[Tue Apr 28 08:44:17 2026] Parsing:  89%
[Tue Apr 28 08:44:17 2026] Parsing:  90%
[Tue Apr 28 08:44:18 2026] Parsing:  90%
[Tue Apr 28 08:44:18 2026] Parsing:  91%
[Tue Apr 28 08:44:19 2026] Parsing:  92%
[Tue Apr 28 08:44:19 2026] Parsing:  92%
[Tue Apr 28 08:44:20 2026] Parsing:  93%
[Tue Apr 28 08:44:20 2026] Parsing:  94%
[Tue Apr 28 08:44:21 2026] Parsing:  94%
[Tue Apr 28 08:44:21 2026] Parsing:  95%
[Tue Apr 28 08:44:22 2026] Parsing:  96%
[Tue Apr 28 08:44:22 2026] Parsing:  96%
[Tue Apr 28 08:44:23 2026] Parsing:  97%
[Tue Apr 28 08:44:23 2026] Parsing:  98%
[Tue Apr 28 08:44:24 2026] Parsing:  98%
[Tue Apr 28 08:44:24 2026] Parsing:  99%
[Tue Apr 28 08:44:29 2026] Parsing: 100%
[Tue Apr 28 08:44:29 2026] Merging:   0%

Parsing (done in 112 seconds )
---------------------------- Merging parallel tasks ----------------------------

[Tue Apr 28 08:44:29 2026] Merging:  14%
[Tue Apr 28 08:44:31 2026] Merging:  28%
[Tue Apr 28 08:44:32 2026] Merging:  42%
[Tue Apr 28 08:44:35 2026] Merging:  57%
[Tue Apr 28 08:44:37 2026] Merging:  71%
[Tue Apr 28 08:44:39 2026] Merging:  85%
[Tue Apr 28 08:44:42 2026] Merging: 100%

Merging (done in 13 seconds )
................................................................................
.                           Total time: 129 seconds                            .
.                           Total memory: 1699.03 Mo                           .
................................................................................
                            ------ END parsing ------
Formating output to GFF3
10324 L2 isoforms with CDS removed (shortest CDS)
0 L2 isoforms wihtout CDS removed (Either no isoform has CDS, we removed those with shortest concatenated exons, or at least one isoform has CDS, we removed those wihtout)

--------------------------- Job done in 162 seconds ----------------------------
command : /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_keep_longest_isoform.pl -f /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.gff3 -o /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.longest_transcript.gff3
date : 04/28/2026 at 08h42m32s
Job done! Bye Bye!


Explanation:
- It uses the `agat_sp_keep_longest_isoform.pl` tool to filter the longest isoform of each transcript.
- The output is saved with a `.longest_transcript.gff` extension.

---

## Step 3: Extracting Protein Sequences Using AGAT
Once you have the longest isoforms, you can extract protein sequences from the corresponding transcript and genome files. This is done using AGAT's `agat_sp_extract_sequences.pl` tool.

In [ ]:
%%bash
agat_sp_extract_sequences.pl \
  -g /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.longest_transcript.gff3 \
  -f /mnt/volume/data/group8/studies/rice/references/osa1_r7.asm.fa \
  -p \
  -o /mnt/volume/data/group8/studies/rice/references/osa1_r7.proteome.longest_transcript.fa

# Remove "*" from protein FASTA
awk '{gsub("\\*", ""); print}' \
  /mnt/volume/data/group8/studies/rice/references/osa1_r7.proteome.longest_transcript.fa \
  > /mnt/volume/data/group8/studies/rice/references/osa1_r7.proteome.longest_transcript.clean.fa \
&& rm /mnt/volume/data/group8/studies/rice/references/osa1_r7.proteome.longest_transcript.fa

 ------------------------------------------------------------------------------
|   Another GFF Analysis Toolkit (AGAT) - Version: v1.7.0                      |
|   https://github.com/NBISweden/AGAT                                          |
|   National Bioinformatics Infrastructure Sweden (NBIS) - www.nbis.se         |
 ------------------------------------------------------------------------------
Using standard /mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/auto/share/dist/AGAT/feature_levels.yaml file
Codon table 1 in use. You can change it using the appropriate parameter.
We will extract the cds sequences.


                          ------ Start parsing ------
-------------------------- parse options and metadata --------------------------
Accessing the feature_levels YAML file
=> Attribute used to group features when no Parent/ID relationship exists (i.e common tag):
	* locus_tag
	* gene_id
=> merge_loci option activated
=> FASTA within the file will be thrown away!
=> Machine information:
	This script is being run by perl v5.32.1
	Bioperl location being used: /mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/Bio/
	Operating system being used: linux
=> Accessing Ontology
	No ontology accessible from the gff file header!
	We use the SOFA ontology distributed with AGAT:
		/mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo
	Read ontology /mnt/volume/home/master22/miniconda3/envs/FunCourse/lib/perl5/site_perl/auto/share/dist/AGAT/so.obo:
		4 root terms, and 2596 total terms, and 1516 leaf terms
	Filtering ontology:
		We found 1861 terms that are sequence_feature or is_a child of it.
--------------------- collecting general data information ----------------------
Parsing file /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.longest_transcript.gff3
=> Number of line in file: 637376
=> Number of comment lines: 1
=> Number of empty lines: 0
=> Fasta included: No
=> Number of features lines: 637375
=> Number of feature lines with 1 fields (while 9 expected): 1
=> Number of feature type (3rd column): 6
	* Level1: 1 => gene
	* level2: 1 => mRNA
	* level3: 4 => CDS exon five_prime_UTR three_prime_UTR
	* unknown: 0 =>
=> Version of the GFF parser selected by AGAT: 3

-------- Start of in-depth analysis (file by chunck 1 CPU - 5 chuncks) ---------

[Tue Apr 28 08:46:37 2026] Parsing:   0%
[Tue Apr 28 08:46:37 2026] Parsing:   0%
[Tue Apr 28 08:46:37 2026] Parsing:   0%
[Tue Apr 28 08:46:38 2026] Parsing:   1%
[Tue Apr 28 08:46:38 2026] Parsing:   2%
[Tue Apr 28 08:46:39 2026] Parsing:   3%
[Tue Apr 28 08:46:39 2026] Parsing:   4%
[Tue Apr 28 08:46:40 2026] Parsing:   5%
[Tue Apr 28 08:46:40 2026] Parsing:   5%
[Tue Apr 28 08:46:41 2026] Parsing:   6%
[Tue Apr 28 08:46:41 2026] Parsing:   7%
[Tue Apr 28 08:46:42 2026] Parsing:   8%
[Tue Apr 28 08:46:42 2026] Parsing:   9%
[Tue Apr 28 08:46:43 2026] Parsing:  10%
[Tue Apr 28 08:46:43 2026] Parsing:  11%
[Tue Apr 28 08:46:44 2026] Parsing:  11%
[Tue Apr 28 08:46:44 2026] Parsing:  12%
[Tue Apr 28 08:46:45 2026] Parsing:  13%
[Tue Apr 28 08:46:45 2026] Parsing:  14%
[Tue Apr 28 08:46:46 2026] Parsing:  15%
[Tue Apr 28 08:46:46 2026] Parsing:  16%
[Tue Apr 28 08:46:47 2026] Parsing:  17%
[Tue Apr 28 08:46:47 2026] Parsing:  17%
[Tue Apr 28 08:46:48 2026] Parsing:  18%
[Tue Apr 28 08:46:48 2026] Parsing:  19%
[Tue Apr 28 08:46:49 2026] Parsing:  20%
[Tue Apr 28 08:46:49 2026] Parsing:  20%
[Tue Apr 28 08:46:56 2026] Parsing:  21%
[Tue Apr 28 08:46:56 2026] Parsing:  21%
[Tue Apr 28 08:46:57 2026] Parsing:  22%
[Tue Apr 28 08:46:57 2026] Parsing:  23%
[Tue Apr 28 08:46:58 2026] Parsing:  24%
[Tue Apr 28 08:46:58 2026] Parsing:  25%
[Tue Apr 28 08:46:59 2026] Parsing:  25%
[Tue Apr 28 08:46:59 2026] Parsing:  26%
[Tue Apr 28 08:47:00 2026] Parsing:  27%
[Tue Apr 28 08:47:00 2026] Parsing:  28%
[Tue Apr 28 08:47:01 2026] Parsing:  29%
[Tue Apr 28 08:47:01 2026] Parsing:  30%
[Tue Apr 28 08:47:02 2026] Parsing:  30%
[Tue Apr 28 08:47:02 2026] Parsing:  31%
[Tue Apr 28 08:47:03 2026] Parsing:  32%
[Tue Apr 28 08:47:03 2026] Parsing:  33%
[Tue Apr 28 08:47:04 2026] Parsing:  34%
[Tue Apr 28 08:47:04 2026] Parsing:  34%
[Tue Apr 28 08:47:05 2026] Parsing:  35%
[Tue Apr 28 08:47:05 2026] Parsing:  36%
[Tue Apr 28 08:47:06 2026] Parsing:  37%
[Tue Apr 28 08:47:06 2026] Parsing:  38%
[Tue Apr 28 08:47:07 2026] Parsing:  39%
[Tue Apr 28 08:47:07 2026] Parsing:  40%
[Tue Apr 28 08:47:08 2026] Parsing:  40%
[Tue Apr 28 08:47:08 2026] Parsing:  41%
[Tue Apr 28 08:47:09 2026] Parsing:  42%
[Tue Apr 28 08:47:09 2026] Parsing:  43%
[Tue Apr 28 08:47:10 2026] Parsing:  43%
[Tue Apr 28 08:47:16 2026] Parsing:  43%
[Tue Apr 28 08:47:17 2026] Parsing:  44%
[Tue Apr 28 08:47:17 2026] Parsing:  45%
[Tue Apr 28 08:47:18 2026] Parsing:  46%
[Tue Apr 28 08:47:18 2026] Parsing:  47%
[Tue Apr 28 08:47:19 2026] Parsing:  48%
[Tue Apr 28 08:47:19 2026] Parsing:  48%
[Tue Apr 28 08:47:20 2026] Parsing:  49%
[Tue Apr 28 08:47:20 2026] Parsing:  50%
[Tue Apr 28 08:47:21 2026] Parsing:  51%
[Tue Apr 28 08:47:21 2026] Parsing:  52%
[Tue Apr 28 08:47:22 2026] Parsing:  53%
[Tue Apr 28 08:47:22 2026] Parsing:  53%
[Tue Apr 28 08:47:23 2026] Parsing:  54%
[Tue Apr 28 08:47:23 2026] Parsing:  55%
[Tue Apr 28 08:47:24 2026] Parsing:  56%
[Tue Apr 28 08:47:24 2026] Parsing:  57%
[Tue Apr 28 08:47:25 2026] Parsing:  58%
[Tue Apr 28 08:47:25 2026] Parsing:  58%
[Tue Apr 28 08:47:26 2026] Parsing:  59%
[Tue Apr 28 08:47:31 2026] Parsing:  60%
[Tue Apr 28 08:47:31 2026] Parsing:  60%
[Tue Apr 28 08:47:32 2026] Parsing:  61%
[Tue Apr 28 08:47:32 2026] Parsing:  62%
[Tue Apr 28 08:47:33 2026] Parsing:  63%
[Tue Apr 28 08:47:33 2026] Parsing:  64%
[Tue Apr 28 08:47:34 2026] Parsing:  65%
[Tue Apr 28 08:47:34 2026] Parsing:  65%
[Tue Apr 28 08:47:35 2026] Parsing:  66%
[Tue Apr 28 08:47:35 2026] Parsing:  67%
[Tue Apr 28 08:47:36 2026] Parsing:  68%
[Tue Apr 28 08:47:36 2026] Parsing:  69%
[Tue Apr 28 08:47:37 2026] Parsing:  70%
[Tue Apr 28 08:47:37 2026] Parsing:  71%
[Tue Apr 28 08:47:38 2026] Parsing:  71%
[Tue Apr 28 08:47:38 2026] Parsing:  72%
[Tue Apr 28 08:47:39 2026] Parsing:  73%
[Tue Apr 28 08:47:39 2026] Parsing:  74%
[Tue Apr 28 08:47:40 2026] Parsing:  75%
[Tue Apr 28 08:47:40 2026] Parsing:  76%
[Tue Apr 28 08:47:41 2026] Parsing:  76%
[Tue Apr 28 08:47:41 2026] Parsing:  77%
[Tue Apr 28 08:47:42 2026] Parsing:  78%
[Tue Apr 28 08:47:42 2026] Parsing:  79%
[Tue Apr 28 08:47:43 2026] Parsing:  80%
[Tue Apr 28 08:47:49 2026] Parsing:  80%
[Tue Apr 28 08:47:50 2026] Parsing:  81%
[Tue Apr 28 08:47:50 2026] Parsing:  82%
[Tue Apr 28 08:47:51 2026] Parsing:  83%
[Tue Apr 28 08:47:51 2026] Parsing:  84%
[Tue Apr 28 08:47:52 2026] Parsing:  85%
[Tue Apr 28 08:47:52 2026] Parsing:  85%
[Tue Apr 28 08:47:53 2026] Parsing:  86%
[Tue Apr 28 08:47:53 2026] Parsing:  87%
[Tue Apr 28 08:47:54 2026] Parsing:  88%
[Tue Apr 28 08:47:54 2026] Parsing:  89%
[Tue Apr 28 08:47:55 2026] Parsing:  90%
[Tue Apr 28 08:47:55 2026] Parsing:  90%
[Tue Apr 28 08:47:56 2026] Parsing:  91%
[Tue Apr 28 08:47:56 2026] Parsing:  92%
[Tue Apr 28 08:47:57 2026] Parsing:  93%
[Tue Apr 28 08:47:57 2026] Parsing:  94%
[Tue Apr 28 08:47:58 2026] Parsing:  94%
[Tue Apr 28 08:47:58 2026] Parsing:  95%
[Tue Apr 28 08:47:59 2026] Parsing:  96%
[Tue Apr 28 08:47:59 2026] Parsing:  97%
[Tue Apr 28 08:48:00 2026] Parsing:  98%
[Tue Apr 28 08:48:00 2026] Parsing:  99%
[Tue Apr 28 08:48:01 2026] Parsing:  99%
[Tue Apr 28 08:48:07 2026] Parsing: 100%

Parsing (done in 90 seconds )
---------------------------- Merging parallel tasks ----------------------------

[Tue Apr 28 08:48:07 2026] Merging:   0%
[Tue Apr 28 08:48:08 2026] Merging:  20%
[Tue Apr 28 08:48:10 2026] Merging:  40%
[Tue Apr 28 08:48:13 2026] Merging:  60%
[Tue Apr 28 08:48:14 2026] Merging:  80%
[Tue Apr 28 08:48:16 2026] Merging: 100%

Merging (done in 9 seconds )
................................................................................
.                           Total time: 104 seconds                            .
.                           Total memory: 1345.68 Mo                           .
................................................................................
                            ------ END parsing ------
Fasta file parsed
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
WARNING: No phase is specify in the CDS. We will assume it start in phase 0. at /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl line 635.
************** Too much WARNING of this type we skip the next **************
55986 cds converted in fasta.

--------------------------- Job done in 140 seconds ----------------------------
command : /mnt/volume/home/master22/miniconda3/envs/FunCourse/bin/agat_sp_extract_sequences.pl -g /mnt/volume/data/group8/studies/rice/references/osa1_r7.all_models.longest_transcript.gff3 -f /mnt/volume/data/group8/studies/rice/references/osa1_r7.asm.fa -p -o /mnt/volume/data/group8/studies/rice/references/osa1_r7.proteome.longest_transcript.fa
date : 04/28/2026 at 08h46m33s
Job done! Bye Bye!


## (Optional, do this if you have a large genome) Chunking the Protein FASTA Files
If you have large protein FASTA files, you may want to split them into smaller chunks, with 3000 sequences per file, to make it easier for downstream tools like Mercator to handle them.

In [ ]:
%%bash
#!/bin/bash

# Set the number of sequences per chunk
sequences_per_chunk=25000
mkdir -p /mnt/volume/data/group8/studies/rice/references/proteome_chunks

# Initialize variables
chunk_counter=1
sequence_counter=0
output_file="/mnt/volume/data/group8/studies/rice/references/proteome_chunks/chunk_${chunk_counter}.fa"

# Process the input FASTA file
awk -v sequences_per_chunk=$sequences_per_chunk -v output_file="$output_file" '
BEGIN {seq_count=0; chunk_count=1}
{
  if (substr($0,1,1) == ">") {
    seq_count++;
    if (seq_count > sequences_per_chunk) {
      chunk_count++;
      seq_count = 1;
      output_file = "/mnt/volume/data/group8/studies/rice/references/proteome_chunks/chunk_" chunk_count ".fa";
    }
  }
  print $0 >> output_file
}
' /mnt/volume/data/group8/studies/rice/references/osa1_r7.proteome.longest_transcript.clean.fa
tree /mnt/volume/data/group8/studies/rice/references/proteome_chunks/

../references/proteome_chunks/
├── chunk_1.fa
├── chunk_2.fa
└── chunk_3.fa

0 directories, 3 files



Explanation:
- This script splits each `.fa` file in the `proteomes` directory into smaller files, each containing 30000 sequences.
- The resulting chunks will be saved in the `proteome_chunks/` directory, with filenames indicating the original file and chunk number.
---

## Step 4: Mercator Web submissions

Now that you've extracted and chunked the protein sequences, they can be used as input for Mercator to perform functional annotation.
1. Visit the [mercator website](https://www.plabipd.de/mercator_main.html) to upload your protein fasta file (one protein fasta at a time). 
2. Include both Prot-scriber and Swissprot annotations
3. give your email id to get the results.

Now sit back and wait for the results. Check your emails. When the run completes, you would get a MapMan mapping file (download this) and an annotated fasta file.
The website also has an enrichment analysis, which requires the mapping file of your organism.

Discuss what a good background is compared to your genes of interest. A safe bet is always to have the full list of genes from the gff file as background genes and differentially expressed genes as genes of Interest.

In [1]:
%%bash
tree /mnt/volume/home/master22/funcourse/workflows/references/*.zip
for file in /mnt/volume/home/master22/funcourse/workflows/references/*.zip; do
  if [[ ! "$file" =~ fasta\.zip$ ]]; then
    unpigz "$file"
  fi
done

/mnt/volume/home/master22/funcourse/workflows/references/GFA-6fdae38acfa659b1343bb5f0a03706b7 (1).zip  [error opening dir]

0 directories, 1 file

## Step 5. Download and concatenate Mercator Mapping file to usable formats

In the steps below, we go from a data structure Mercator likes to a format that we can work with faster.

In [ ]:
%%bash
set -euo pipefail

OUT=/mnt/volume/data/group8/studies/rice/references/Mercator_Mapped_file.tsv
> "$OUT"

# Unzip GFA results (if not already unzipped)
for zip in /mnt/volume/home/master22/funcourse/workflows/references/GFA-*.zip; do
  unzip -p "$zip" >> "$OUT"
done

head /mnt/volume/data/group8/studies/rice/references/Mercator_Mapped_file.tsv
ls /mnt/volume/data/group8/studies/rice/references/Mercator_Mapped_file.tsv -lah

Above is a complicated structure that Mercator gives us, lets convert it into a collection of csv files that are also a list of genes.

In [5]:
%%bash
head /mnt/volume/home/master22/funcourse/workflows/references/Mercator_Mapped_file.tsv

BINCODE	NAME	IDENTIFIER	DESCRIPTION	TYPE
'1'	'Photosynthesis'	''	''
'1.1'	'Photosynthesis.photophosphorylation'	''	''
'1.1.1'	'Photosynthesis.photophosphorylation.photosystem II'	''	''
'1.1.1.1'	'Photosynthesis.photophosphorylation.photosystem II.LHC-II complex'	''	''
'1.1.1.1.1'	'Photosynthesis.photophosphorylation.photosystem II.LHC-II complex.component *(LHCb1/2/3)'	'loc_os01g41710.1'	'mercator4v8.0: component *(LHCb1/2/3) of LHC-II complex & swissprot: Chlorophyll a-b binding protein 2, chloroplastic OS=Oryza sativa subsp. japonica  & original description: gene=LOC_Os01g41710 seq_id=Chr1 type=cds'	T
'1.1.1.1.1'	'Photosynthesis.photophosphorylation.photosystem II.LHC-II complex.component *(LHCb1/2/3)'	'loc_os01g52240.1'	'mercator4v8.0: component *(LHCb1/2/3) of LHC-II complex & swissprot: Chlorophyll a-b binding protein 1, chloroplastic OS=Oryza sativa subsp. japonica  & original description: gene=LOC_Os01g52240 seq_id=Chr1 type=cds'	T
'1.1.1.1.1'	'Photosynthesis.photophosphorylation.photosystem II.LHC-II complex.component *(LHCb1/2/3)'	'loc_os03g39610.1'	'mercator4v8.0: component *(LHCb1/2/3) of LHC-II complex & swissprot: Chlorophyll a-b binding protein, chloroplastic OS=Oryza sativa subsp. japonica  & original description: gene=LOC_Os03g39610 seq_id=Chr3 type=cds'	T
'1.1.1.1.1'	'Photosynthesis.photophosphorylation.photosystem II.LHC-II complex.component *(LHCb1/2/3)'	'loc_os07g37550.1'	'mercator4v8.0: component *(LHCb1/2/3) of LHC-II complex & swissprot: Chlorophyll a-b binding protein of LHCII type III, chloroplastic OS=Hordeum vulgare  & original description: gene=LOC_Os07g37550 seq_id=Chr7 type=cds'	T
'1.1.1.1.1'	'Photosynthesis.photophosphorylation.photosystem II.LHC-II complex.component *(LHCb1/2/3)'	'loc_os09g17740.1'	'mercator4v8.0: component *(LHCb1/2/3) of LHC-II complex & swissprot: Chlorophyll a-b binding protein 1, chloroplastic OS=Oryza sativa subsp. japonica  & original description: gene=LOC_Os09g17740 seq_id=Chr9 type=cds'	T

In [2]:
import pandas as pd
import sys

def parse_and_combine_batch_files(batch_files, tx2gene_file):
    """
    Parses batch files, extracts transcript annotations, maps to gene IDs using tx2gene,
    and returns a cleaned dataframe.
    """

    def parse_batch_file(file):
        """Extracts transcript-level annotations and Mercator bin assignments."""
        with open(file, 'r') as f:
            lines = f.readlines()

        data = []
        for line in lines:
            fields = line.strip().split("\t")
            
            # Check if line contains a valid transcript ID
            if len(fields) > 4:
                ID = fields[2].replace("'", "")
                name_field = fields[1].replace("'", "")
                mercator_levels = name_field.split(".")
                
                # Extract annotations from DESCRIPTION column
                description = fields[3].replace("'", "")
                annotations = description.split('&')
                prot_scriber_annotation = ''
                swissprot_annotation = ''
                
                for annotation in annotations:
                    key_value = annotation.split(':')
                    if 'prot-scriber' in key_value[0]:
                        prot_scriber_annotation = key_value[1]
                    elif 'swissprot' in key_value[0]:
                        swissprot_annotation = key_value[1]

                # Ensure at least 8 Mercator levels
                while len(mercator_levels) < 8:
                    mercator_levels.append('')
                
                # Append extracted data
                data.append([ID] + mercator_levels + [prot_scriber_annotation, swissprot_annotation])

        columns = ["IDENTIFIER"] + [f"level{i}" for i in range(1, 9)] + ["protscriber", "swissprot"]
        return pd.DataFrame(data, columns=columns)
    
    # Parse batch files
    df_list = [parse_batch_file(file) for file in batch_files]
    combined_data = pd.concat(df_list, ignore_index=True)
    
    # Debug: Check initial extracted data
    print("Extracted Data Preview (Before Mapping):")
    print(combined_data.head())
    sys.stdout.flush()

    # Load transcript-to-gene mapping file
    tx2gene = pd.read_csv(tx2gene_file)

    # Remove "transcript:" prefix from IDENTIFIER before merging
    combined_data["IDENTIFIER"] = combined_data["IDENTIFIER"].astype(str).str.replace("transcript:", "", regex=True).str.strip().str.lower()
    
    # Normalize transcript IDs in both dataframes
    tx2gene["ID"] = tx2gene["ID"].astype(str).str.replace("transcript:", "", regex=True).str.strip().str.lower()
    tx2gene["gene_id"] = tx2gene["gene_id"].astype(str).str.strip()

    # Merge with tx2gene mapping
    combined_data = combined_data.merge(tx2gene, left_on="IDENTIFIER", right_on="ID", how="left")

    # Debug: Check how many identifiers were mapped
    mapped_count = combined_data["gene_id"].notnull().sum()
    unmapped_count = combined_data["gene_id"].isnull().sum()
    print(f"Successfully mapped transcripts to genes: {mapped_count}")
    print(f"Unmapped transcripts (IDENTIFIER is NaN after merge): {unmapped_count}")
    sys.stdout.flush()

    # Remove rows where merging failed (NaN IDENTIFIERs)
    combined_data = combined_data[combined_data["gene_id"].notnull()].copy()

    # Drop old columns and rename IDENTIFIER column
    combined_data.drop(columns=["IDENTIFIER", "ID"], inplace=True)
    combined_data.rename(columns={"gene_id": "IDENTIFIER"}, inplace=True)

    # Debug: Check cleaned data
    print("Final DataFrame after Mapping:")
    print(combined_data.head())
    print(f"Total valid gene rows: {len(combined_data)}")
    sys.stdout.flush()

    return combined_data

# List of batch files
batch_files = ["/mnt/volume/home/master22/funcourse/workflows/references/Mercator_Mapped_file.tsv"]
tx2gene_file = "/mnt/volume/home/master22/funcourse/workflows/references/tx2gene.csv"

# Parse batch files and map transcripts to genes
plantTerms = parse_and_combine_batch_files(batch_files, tx2gene_file)

# Remove unwanted annotation
plantTerms = plantTerms[plantTerms.level1 != 'no annotation'].drop_duplicates()
plantTerms = plantTerms.drop_duplicates(subset=['IDENTIFIER'])

Extracted Data Preview (Before Mapping):
         IDENTIFIER          level1                level2          level3  \
0        IDENTIFIER            NAME
1  loc_os01g41710.1  Photosynthesis  photophosphorylation  photosystem II
2  loc_os01g52240.1  Photosynthesis  photophosphorylation  photosystem II
3  loc_os03g39610.1  Photosynthesis  photophosphorylation  photosystem II
4  loc_os07g37550.1  Photosynthesis  photophosphorylation  photosystem II

           level4                  level5 level6 level7 level8 protscriber  \
0
1  LHC-II complex  component *(LHCb1/2/3)
2  LHC-II complex  component *(LHCb1/2/3)
3  LHC-II complex  component *(LHCb1/2/3)
4  LHC-II complex  component *(LHCb1/2/3)

                                           swissprot
0
1   Chlorophyll a-b binding protein 2, chloroplas...
2   Chlorophyll a-b binding protein 1, chloroplas...
3   Chlorophyll a-b binding protein, chloroplasti...
4   Chlorophyll a-b binding protein of LHCII type...

Successfully mapped transcripts to genes: 61173
Unmapped transcripts (IDENTIFIER is NaN after merge): 1
Final DataFrame after Mapping:
           level1                level2          level3          level4  \
1  Photosynthesis  photophosphorylation  photosystem II  LHC-II complex
2  Photosynthesis  photophosphorylation  photosystem II  LHC-II complex
3  Photosynthesis  photophosphorylation  photosystem II  LHC-II complex
4  Photosynthesis  photophosphorylation  photosystem II  LHC-II complex
5  Photosynthesis  photophosphorylation  photosystem II  LHC-II complex

                   level5 level6 level7 level8 protscriber  \
1  component *(LHCb1/2/3)
2  component *(LHCb1/2/3)
3  component *(LHCb1/2/3)
4  component *(LHCb1/2/3)
5  component *(LHCb1/2/3)

                                           swissprot      IDENTIFIER
1   Chlorophyll a-b binding protein 2, chloroplas...  LOC_Os01g41710
2   Chlorophyll a-b binding protein 1, chloroplas...  LOC_Os01g52240
3   Chlorophyll a-b binding protein, chloroplasti...  LOC_Os03g39610
4   Chlorophyll a-b binding protein of LHCII type...  LOC_Os07g37550
5   Chlorophyll a-b binding protein 1, chloroplas...  LOC_Os09g17740
Total valid gene rows: 61173

Check if the cell above runs, debug it and resolve any issues before the next cell, where we would write it down into all the files that reflect each level of depth.

In [3]:
import pandas as pd
import os
# List of tables to process
tables = {
    'plantTerms': plantTerms
}
# Columns to process
columns = ["level1", "level2", "level3", "level4", "level5", "level6", "level7", "level8", "protscriber", "swissprot"]
for table_name, table in tables.items():
    for column in columns:
        # Check if the column exists in the table to avoid KeyError
        if column in table.columns:
            # Process the table
            processed_table = table[["IDENTIFIER", column]]
            processed_table = processed_table[processed_table[column].notnull()].drop_duplicates()
            
            # Construct the file name
            filename = f"../references/mercator_{column}_{table_name}.csv"
            
            # Save to CSV
            processed_table.to_csv(filename, sep=',', index=False, header=False)
            print(f"Saved {filename}")

Saved ../references/mercator_level1_plantTerms.csv
Saved ../references/mercator_level2_plantTerms.csv
Saved ../references/mercator_level3_plantTerms.csv
Saved ../references/mercator_level4_plantTerms.csv
Saved ../references/mercator_level5_plantTerms.csv
Saved ../references/mercator_level6_plantTerms.csv
Saved ../references/mercator_level7_plantTerms.csv
Saved ../references/mercator_level8_plantTerms.csv
Saved ../references/mercator_protscriber_plantTerms.csv
Saved ../references/mercator_swissprot_plantTerms.csv

## Step 6 Functional Enrichment with Mercator and clusterProfiler.

Next up, we use R clusterprofiler to look for enrichments and to plot them out. Don't forget to change your kernels. Also, please install cluster profiler by typing the following in your conda environment: 

> **Warning**  
> We need a new R environment to operate clusterprofiler well. Please remember to change the kernel.

`conda create -n FunCourse1 bioconda::bioconductor-clusterprofiler conda-forge::r-stringr conda-forge::r-dplyr conda-forge::r-ggplot2 conda-forge::r-irkernel  conda-forge::r-tidyverse -y`

In [16]:
library(tidyverse)
library("clusterProfiler")

clusterProfiler v4.14.0 Learn more at https://yulab-smu.top/contribution-knowledge-mining/

Please cite:

S Xu, E Hu, Y Cai, Z Xie, X Luo, L Zhan, W Tang, Q Wang, B Liu, R Wang,
W Xie, T Wu, L Xie, G Yu. Using clusterProfiler to characterize
multiomics data. Nature Protocols. 2024, 19(11):3292-3320


Attaching package: ‘clusterProfiler’


The following object is masked from ‘package:purrr’:

    simplify


The following object is masked from ‘package:stats’:

    filter

In [2]:
print(getwd())

[1] "/mnt/volume/home/master22/funcourse/workflows/scripts"

In [3]:
setwd("/mnt/volume/home/master22/funcourse/runs/FunCourse/")

In [4]:
DEGs <- list.files(pattern = ("deseq2_day4_filtered_results.csv"))
str(DEGs)

 chr "deseq2_day4_filtered_results.csv"

In [8]:
datalist_deg = list()
for (i in DEGs) {
    deg_df <- read.table(i, sep = ",", header = TRUE, stringsAsFactors = FALSE)
    deg_df <- deg_df %>%
        rename(Gene = 1) %>%      # take first column, call it Gene
        select(Gene, padj) %>%
        filter(!is.na(padj), padj < 0.05)
        datalist_deg[[i]] <- deg_df
}    
gene_contrast <- do.call(rbind, datalist_deg)

In [9]:
rownames(gene_contrast) <- NULL
dim(gene_contrast)
head(gene_contrast)

[1] 6157    2

  Gene           padj
1 LOC_Os06g50880 1.190073e-86
2 LOC_Os03g10780 2.744655e-66
3 LOC_Os03g10460 6.242776e-66
4 LOC_Os04g59480 3.865691e-65
5 LOC_Os01g49026 1.106510e-62
6 LOC_Os01g15860 1.151292e-61

In [10]:
setwd("/mnt/volume/home/master22/funcourse/workflows/references/")
mercator_names <- list.files(pattern = ("mercator*"))
print(mercator_names)

 [1] "mercator_level1_plantTerms.csv"      "mercator_level2_plantTerms.csv"
 [3] "mercator_level3_plantTerms.csv"      "mercator_level4_plantTerms.csv"
 [5] "mercator_level5_plantTerms.csv"      "mercator_level6_plantTerms.csv"
 [7] "mercator_level7_plantTerms.csv"      "mercator_level8_plantTerms.csv"
 [9] "mercator_protscriber_plantTerms.csv" "mercator_swissprot_plantTerms.csv"

In [11]:
str(mercator_names)

 chr [1:10] "mercator_level1_plantTerms.csv" ...

In [12]:


datalist_term2gene = list()
for (i in mercator_names) {
        mercator_df <- read.table(i, sep=",", stringsAsFactors = FALSE)
        mercator_df <- mercator_df %>% 
                    mutate(Filename = paste0(i)) %>% 
                    rename(Term = V2, Gene = V1) %>% 
                    #mutate(Level = str_extract(Filename, regex("level[1-8]"))) %>% 
                    mutate(Level = str_split_i(Filename, "_", 2)) #%>%
                    #select(-Filename)
        datalist_term2gene[[i]] <- mercator_df
}
term2gene <- do.call(rbind, datalist_term2gene)
rownames(term2gene) <- NULL
dim(term2gene)
head(term2gene)
##
print("Imports are finished")

[1] 559860      4

  Gene           Term           Filename                       Level
1 LOC_Os01g41710 Photosynthesis mercator_level1_plantTerms.csv level1
2 LOC_Os01g52240 Photosynthesis mercator_level1_plantTerms.csv level1
3 LOC_Os03g39610 Photosynthesis mercator_level1_plantTerms.csv level1
4 LOC_Os07g37550 Photosynthesis mercator_level1_plantTerms.csv level1
5 LOC_Os09g17740 Photosynthesis mercator_level1_plantTerms.csv level1
6 LOC_Os07g37240 Photosynthesis mercator_level1_plantTerms.csv level1

[1] "Imports are finished"

In [13]:
term2gene

       Gene           Term            Filename
1      LOC_Os01g41710 Photosynthesis  mercator_level1_plantTerms.csv
2      LOC_Os01g52240 Photosynthesis  mercator_level1_plantTerms.csv
3      LOC_Os03g39610 Photosynthesis  mercator_level1_plantTerms.csv
4      LOC_Os07g37550 Photosynthesis  mercator_level1_plantTerms.csv
5      LOC_Os09g17740 Photosynthesis  mercator_level1_plantTerms.csv
6      LOC_Os07g37240 Photosynthesis  mercator_level1_plantTerms.csv
7      LOC_Os11g13890 Photosynthesis  mercator_level1_plantTerms.csv
8      LOC_Os04g38410 Photosynthesis  mercator_level1_plantTerms.csv
9      LOC_Os09g12540 Photosynthesis  mercator_level1_plantTerms.csv
10     LOC_Os04g16770 Photosynthesis  mercator_level1_plantTerms.csv
11     LOC_Os08g35420 Photosynthesis  mercator_level1_plantTerms.csv
12     LOC_Os10g21192 Photosynthesis  mercator_level1_plantTerms.csv
13     LOC_Os02g24634 Photosynthesis  mercator_level1_plantTerms.csv
14     LOC_Os04g16872 Photosynthesis  mercator_level1_plantTerms.csv
15     LOC_Os10g41689 Photosynthesis  mercator_level1_plantTerms.csv
16     LOC_Os06g39708 Photosynthesis  mercator_level1_plantTerms.csv
17     LOC_Os10g21310 Photosynthesis  mercator_level1_plantTerms.csv
18     LOC_Os02g24632 Photosynthesis  mercator_level1_plantTerms.csv
19     LOC_Os04g16874 Photosynthesis  mercator_level1_plantTerms.csv
20     LOC_Os10g21212 Photosynthesis  mercator_level1_plantTerms.csv
21     LOC_Os06g39728 Photosynthesis  mercator_level1_plantTerms.csv
22     LOC_Os08g15322 Photosynthesis  mercator_level1_plantTerms.csv
23     LOC_Os10g21298 Photosynthesis  mercator_level1_plantTerms.csv
24     LOC_Os01g31690 Photosynthesis  mercator_level1_plantTerms.csv
25     LOC_Os07g04840 Photosynthesis  mercator_level1_plantTerms.csv
26     LOC_Os07g36080 Photosynthesis  mercator_level1_plantTerms.csv
27     LOC_Os04g16848 Photosynthesis  mercator_level1_plantTerms.csv
28     LOC_Os06g39704 Photosynthesis  mercator_level1_plantTerms.csv
29     LOC_Os08g15296 Photosynthesis  mercator_level1_plantTerms.csv
30     LOC_Os10g21322 Photosynthesis  mercator_level1_plantTerms.csv
⋮      ⋮              ⋮               ⋮
559831 LOC_Os12g43480  no annotation  mercator_swissprot_plantTerms.csv
559832 LOC_Os12g43500  no annotation  mercator_swissprot_plantTerms.csv
559833 LOC_Os12g43510  no annotation  mercator_swissprot_plantTerms.csv
559834 LOC_Os12g43540  no annotation  mercator_swissprot_plantTerms.csv
559835 LOC_Os12g43564  no annotation  mercator_swissprot_plantTerms.csv
559836 LOC_Os12g43570  no annotation  mercator_swissprot_plantTerms.csv
559837 LOC_Os12g43580  no annotation  mercator_swissprot_plantTerms.csv
559838 LOC_Os12g43610  no annotation  mercator_swissprot_plantTerms.csv
559839 LOC_Os12g43680  no annotation  mercator_swissprot_plantTerms.csv
559840 LOC_Os12g43710  no annotation  mercator_swissprot_plantTerms.csv
559841 LOC_Os12g43730  no annotation  mercator_swissprot_plantTerms.csv
559842 LOC_Os12g43750  no annotation  mercator_swissprot_plantTerms.csv
559843 LOC_Os12g43760  no annotation  mercator_swissprot_plantTerms.csv
559844 LOC_Os12g43770  no annotation  mercator_swissprot_plantTerms.csv
559845 LOC_Os12g43790  no annotation  mercator_swissprot_plantTerms.csv
559846 LOC_Os12g43810  no annotation  mercator_swissprot_plantTerms.csv
559847 LOC_Os12g43840  no annotation  mercator_swissprot_plantTerms.csv
559848 LOC_Os12g43860  no annotation  mercator_swissprot_plantTerms.csv
559849 LOC_Os12g43870  no annotation  mercator_swissprot_plantTerms.csv
559850 LOC_Os12g43900  no annotation  mercator_swissprot_plantTerms.csv
559851 LOC_Os12g43910  no annotation  mercator_swissprot_plantTerms.csv
559852 LOC_Os12g43960  no annotation  mercator_swissprot_plantTerms.csv
559853 LOC_Os12g43990  no annotation  mercator_swissprot_plantTerms.csv
559854 LOC_Os12g44040  no annotation  mercator_swissprot_plantTerms.csv
559855 LOC_Os12g44120  no annotation  mercator_swissprot_plantTerms.csv
559856 LOC_Os12g44130  no annotation  mercator_swissprot_plantTerms.csv
559857 LOC_Os12g44160  no annotation  mercator_swissprot_plantTerms.csv
559858 LOC_Os12g44260  no annotation  mercator_swissprot_plantTerms.csv
559859 LOC_Os12g44270  no annotation  mercator_swissprot_plantTerms.csv
559860 LOC_Os12g44280  no annotation  mercator_swissprot_plantTerms.csv
       Level
1      level1
2      level1
3      level1
4      level1
5      level1
6      level1
7      level1
8      level1
9      level1
10     level1
11     level1
12     level1
13     level1
14     level1
15     level1
16     level1
17     level1
18     level1
19     level1
20     level1
21     level1
22     level1
23     level1
24     level1
25     level1
26     level1
27     level1
28     level1
29     level1
30     level1
⋮      ⋮
559831 swissprot
559832 swissprot
559833 swissprot
559834 swissprot
559835 swissprot
559836 swissprot
559837 swissprot
559838 swissprot
559839 swissprot
559840 swissprot
559841 swissprot
559842 swissprot
559843 swissprot
559844 swissprot
559845 swissprot
559846 swissprot
559847 swissprot
559848 swissprot
559849 swissprot
559850 swissprot
559851 swissprot
559852 swissprot
559853 swissprot
559854 swissprot
559855 swissprot
559856 swissprot
559857 swissprot
559858 swissprot
559859 swissprot
559860 swissprot

In [14]:
# 
setwd("/mnt/volume/home/master22/funcourse/workflows/scripts/")

Reference code from course

In [ ]:
#code executed separately in above cells 
#library(tidyverse)
library("clusterProfiler")
# import gene_contrast table
print(getwd())
setwd("/mnt/volume/home/master22/funcourse/runs/FunCourse/")
DEGs <- list.files(pattern = ("deseq2_filtered_results.csv"))
str(DEGs)
datalist_deg = list()
for (i in DEGs) {
    deg_df <- read.table(i, sep = ",", header = TRUE, stringsAsFactors = FALSE)
    deg_df <- deg_df %>%
        rename(Gene = 1) %>%      # take first column, call it Gene
        select(Gene, padj) %>%
        filter(!is.na(padj), padj < 0.05)
        datalist_deg[[i]] <- deg_df
}    
gene_contrast <- do.call(rbind, datalist_deg)
rownames(gene_contrast) <- NULL
dim(gene_contrast)
head(gene_contrast)
# import term2gene tables
# and fuse them into single df per species
setwd("../../workflows/references/")
mercator_names <- list.files(pattern = ("mercator*"))
str(mercator_names)
datalist_term2gene = list()
for (i in mercator_names) {
        mercator_df <- read.table(i, sep=",", stringsAsFactors = FALSE)
        mercator_df <- mercator_df %>% 
                    mutate(Filename = paste0(i)) %>% 
                    rename(Term = V2, Gene = V1) %>% 
                    #mutate(Level = str_extract(Filename, regex("level[1-8]"))) %>% 
                    mutate(Level = str_split_i(Filename, "_", 2)) #%>%
                    #select(-Filename)
        datalist_term2gene[[i]] <- mercator_df
}
term2gene <- do.call(rbind, datalist_term2gene)
rownames(term2gene) <- NULL
dim(term2gene)
head(term2gene)
##
print("Imports are finished")
# 
setwd("../scripts/")

In [15]:
dim(term2gene)

[1] 559860      4

In [20]:
# Define functional levels
levels <- c("level1", "level2", "level3", "level4", "level5", 
            "level6", "level7", "level8", "protscriber", "swissprot")

# Check the contents of term2gene before filtering
print("Summary of term2gene before filtering:")
print(str(term2gene))
print("Unique levels in term2gene:")
print(unique(term2gene$Level))
print("Unique filenames in term2gene:")
print(unique(term2gene$Filename))
# Extract gene list from filtered DEGs
genelist <- unique(gene_contrast$Gene)

[1] "Summary of term2gene before filtering:"
'data.frame':	559860 obs. of  4 variables:
 $ Gene    : chr  "LOC_Os01g41710" "LOC_Os01g52240" "LOC_Os03g39610" "LOC_Os07g37550" ...
 $ Term    : chr  "Photosynthesis" "Photosynthesis" "Photosynthesis" "Photosynthesis" ...
 $ Filename: chr  "mercator_level1_plantTerms.csv" "mercator_level1_plantTerms.csv" "mercator_level1_plantTerms.csv" "mercator_level1_plantTerms.csv" ...
 $ Level   : chr  "level1" "level1" "level1" "level1" ...
NULL
[1] "Unique levels in term2gene:"
 [1] "level1"      "level2"      "level3"      "level4"      "level5"
 [6] "level6"      "level7"      "level8"      "protscriber" "swissprot"
[1] "Unique filenames in term2gene:"
 [1] "mercator_level1_plantTerms.csv"      "mercator_level2_plantTerms.csv"
 [3] "mercator_level3_plantTerms.csv"      "mercator_level4_plantTerms.csv"
 [5] "mercator_level5_plantTerms.csv"      "mercator_level6_plantTerms.csv"
 [7] "mercator_level7_plantTerms.csv"      "mercator_level8_plantTerms.csv"
 [9] "mercator_protscriber_plantTerms.csv" "mercator_swissprot_plantTerms.csv"

In [21]:
dir.create("/mnt/volume/home/master22/funcourse/runs/FunCourse/enrichments/")
# Loop over levels and run enrichment analysis
for (level in levels) {
    print(paste("Processing enrichment for", level))

    # Find matching term2gene enrichment tables
    tempset <- term2gene %>%
                filter(str_detect(Filename, "_plantTerms.csv")) %>%
                filter(Level == level) %>%
                select(Term, Gene)

    # Debug: Check if the filtered term2gene table has any rows
    print(paste("Filtered term2gene table for", level, "has", nrow(tempset), "rows"))
    if (nrow(tempset) > 0) {
        print("First few rows of filtered term2gene:")
        print(head(tempset, 3))
        
        # Run enrichment analysis
        enrich <- enricher(
                    gene = genelist,
                    pvalueCutoff = 0.1,
                    pAdjustMethod = "BH",
                    minGSSize = 10,
                    maxGSSize = 500,
                    qvalueCutoff = 0.2,
                    TERM2GENE = tempset)

        #print("Enrichment results structure:")
        #print(str(enrich))
        res <- data.frame(enrich)

        #print("First few rows of enrichment results:")
        #print(head(res))
        
        # Save results if enrichment results exist
        if (nrow(res) >= 1) {
            filename <- paste0("/mnt/volume/home/master22/funcourse/runs/FunCourse/enrichments/",level, "_DESeq2_Mercator_clusterprof.csv")
            write.csv(res, file = filename)

            plot_filename <- paste0("/mnt/volume/home/master22/funcourse/runs/FunCourse/enrichments/",level, "_DESeq2_Mercator_plot.pdf")
            ggsave(filename = plot_filename, 
                   plot = dotplot(enrich), 
                   width = 15, height = 10)
        }
    } else {
        print(paste("No enrichment data found for", level, "skipping."))
        next
    }
}

print("All processing completed.")

Warning message in dir.create("/mnt/volume/home/master22/funcourse/runs/FunCourse/enrichments/"):
“'/mnt/volume/home/master22/funcourse/runs/FunCourse/enrichments' already exists”

[1] "Processing enrichment for level1"
[1] "Filtered term2gene table for level1 has 55986 rows"
[1] "First few rows of filtered term2gene:"
            Term           Gene
1 Photosynthesis LOC_Os01g41710
2 Photosynthesis LOC_Os01g52240
3 Photosynthesis LOC_Os03g39610
[1] "Processing enrichment for level2"
[1] "Filtered term2gene table for level2 has 55986 rows"
[1] "First few rows of filtered term2gene:"
                  Term           Gene
1 photophosphorylation LOC_Os01g41710
2 photophosphorylation LOC_Os01g52240
3 photophosphorylation LOC_Os03g39610
[1] "Processing enrichment for level3"
[1] "Filtered term2gene table for level3 has 55986 rows"
[1] "First few rows of filtered term2gene:"
            Term           Gene
1 photosystem II LOC_Os01g41710
2 photosystem II LOC_Os01g52240
3 photosystem II LOC_Os03g39610
[1] "Processing enrichment for level4"
[1] "Filtered term2gene table for level4 has 55986 rows"
[1] "First few rows of filtered term2gene:"
            Term           Gene
1 LHC-II complex LOC_Os01g41710
2 LHC-II complex LOC_Os01g52240
3 LHC-II complex LOC_Os03g39610
[1] "Processing enrichment for level5"
[1] "Filtered term2gene table for level5 has 55986 rows"
[1] "First few rows of filtered term2gene:"
                    Term           Gene
1 component *(LHCb1/2/3) LOC_Os01g41710
2 component *(LHCb1/2/3) LOC_Os01g52240
3 component *(LHCb1/2/3) LOC_Os03g39610
[1] "Processing enrichment for level6"
[1] "Filtered term2gene table for level6 has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1      LOC_Os01g41710
2      LOC_Os01g52240
3      LOC_Os03g39610
[1] "Processing enrichment for level7"
[1] "Filtered term2gene table for level7 has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1      LOC_Os01g41710
2      LOC_Os01g52240
3      LOC_Os03g39610
[1] "Processing enrichment for level8"
[1] "Filtered term2gene table for level8 has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1      LOC_Os01g41710
2      LOC_Os01g52240
3      LOC_Os03g39610

No gene sets have size between 10 and 500 ...

--> return NULL...

[1] "Processing enrichment for protscriber"
[1] "Filtered term2gene table for protscriber has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1 <NA> LOC_Os01g41710
2 <NA> LOC_Os01g52240
3 <NA> LOC_Os03g39610

--> No gene can be mapped....

--> Expected input gene ID:

--> return NULL...

[1] "Processing enrichment for swissprot"
[1] "Filtered term2gene table for swissprot has 55986 rows"
[1] "First few rows of filtered term2gene:"
                                                                                 Term
1  Chlorophyll a-b binding protein 2, chloroplastic OS=Oryza sativa subsp. japonica
2  Chlorophyll a-b binding protein 1, chloroplastic OS=Oryza sativa subsp. japonica
3    Chlorophyll a-b binding protein, chloroplastic OS=Oryza sativa subsp. japonica
            Gene
1 LOC_Os01g41710
2 LOC_Os01g52240
3 LOC_Os03g39610
[1] "All processing completed."

reference code from course

In [ ]:
# implemented this code separately in above cells, but here is the full code for reference.
# Define functional levels
levels <- c("level1", "level2", "level3", "level4", "level5", 
            "level6", "level7", "level8", "protscriber", "swissprot")

# Check the contents of term2gene before filtering
print("Summary of term2gene before filtering:")
print(str(term2gene))
print("Unique levels in term2gene:")
print(unique(term2gene$Level))
print("Unique filenames in term2gene:")
print(unique(term2gene$Filename))
# Extract gene list from filtered DEGs
genelist <- unique(gene_contrast$Gene)
dir.create("../../runs/FunCourse/enrichments/")
# Loop over levels and run enrichment analysis
for (level in levels) {
    print(paste("Processing enrichment for", level))

    # Find matching term2gene enrichment tables
    tempset <- term2gene %>%
                filter(str_detect(Filename, "_plantTerms.csv")) %>%
                filter(Level == level) %>%
                select(Term, Gene)

    # Debug: Check if the filtered term2gene table has any rows
    print(paste("Filtered term2gene table for", level, "has", nrow(tempset), "rows"))
    if (nrow(tempset) > 0) {
        print("First few rows of filtered term2gene:")
        print(head(tempset, 3))
        
        # Run enrichment analysis
        enrich <- enricher(
                    gene = genelist,
                    pvalueCutoff = 0.1,
                    pAdjustMethod = "BH",
                    minGSSize = 10,
                    maxGSSize = 500,
                    qvalueCutoff = 0.2,
                    TERM2GENE = tempset)

        #print("Enrichment results structure:")
        #print(str(enrich))
        res <- data.frame(enrich)

        #print("First few rows of enrichment results:")
        #print(head(res))
        
        # Save results if enrichment results exist
        if (nrow(res) >= 1) {
            filename <- paste0("../../runs/FunCourse/enrichments/",level, "_DESeq2_Mercator_clusterprof.csv")
            write.csv(res, file = filename)

            plot_filename <- paste0("../../runs/FunCourse/enrichments/",level, "_DESeq2_Mercator_plot.pdf")
            ggsave(filename = plot_filename, 
                   plot = dotplot(enrich), 
                   width = 15, height = 10)
        }
    } else {
        print(paste("No enrichment data found for", level, "skipping."))
        next
    }
}

print("All processing completed.")

[1] "Summary of term2gene before filtering:"
'data.frame':	559860 obs. of  4 variables:
 $ Gene    : chr  "LOC_Os11g37130" "LOC_Os12g29570" "LOC_Os12g18640" "LOC_Os12g08730" ...
 $ Term    : chr  "Photosynthesis" "Photosynthesis" "Photosynthesis" "Photosynthesis" ...
 $ Filename: chr  "mercator_level1_plantTerms.csv" "mercator_level1_plantTerms.csv" "mercator_level1_plantTerms.csv" "mercator_level1_plantTerms.csv" ...
 $ Level   : chr  "level1" "level1" "level1" "level1" ...
NULL
[1] "Unique levels in term2gene:"
 [1] "level1"      "level2"      "level3"      "level4"      "level5"
 [6] "level6"      "level7"      "level8"      "protscriber" "swissprot"
[1] "Unique filenames in term2gene:"
 [1] "mercator_level1_plantTerms.csv"      "mercator_level2_plantTerms.csv"
 [3] "mercator_level3_plantTerms.csv"      "mercator_level4_plantTerms.csv"
 [5] "mercator_level5_plantTerms.csv"      "mercator_level6_plantTerms.csv"
 [7] "mercator_level7_plantTerms.csv"      "mercator_level8_plantTerms.csv"
 [9] "mercator_protscriber_plantTerms.csv" "mercator_swissprot_plantTerms.csv"

Warning message in dir.create("../../runs/FunCourse/enrichments/"):
“'../../runs/FunCourse/enrichments' already exists”

[1] "Processing enrichment for level1"
[1] "Filtered term2gene table for level1 has 55986 rows"
[1] "First few rows of filtered term2gene:"
            Term           Gene
1 Photosynthesis LOC_Os11g37130
2 Photosynthesis LOC_Os12g29570
3 Photosynthesis LOC_Os12g18640
[1] "Processing enrichment for level2"
[1] "Filtered term2gene table for level2 has 55986 rows"
[1] "First few rows of filtered term2gene:"
                  Term           Gene
1 photophosphorylation LOC_Os11g37130
2 photophosphorylation LOC_Os12g29570
3 photophosphorylation LOC_Os12g18640
[1] "Processing enrichment for level3"
[1] "Filtered term2gene table for level3 has 55986 rows"
[1] "First few rows of filtered term2gene:"
            Term           Gene
1 photosystem II LOC_Os11g37130
2 photosystem II LOC_Os12g29570
3 photosystem II LOC_Os12g18640
[1] "Processing enrichment for level4"
[1] "Filtered term2gene table for level4 has 55986 rows"
[1] "First few rows of filtered term2gene:"
      Term           Gene
1 assembly LOC_Os11g37130
2 assembly LOC_Os12g29570
3 assembly LOC_Os12g18640
[1] "Processing enrichment for level5"
[1] "Filtered term2gene table for level5 has 55986 rows"
[1] "First few rows of filtered term2gene:"
                                     Term           Gene
1               assembly factor *(HCF106) LOC_Os11g37130
2      HCF244-OHP assembly factor complex LOC_Os12g29570
3 psbJ/psbN-translation activator *(LPE1) LOC_Os12g18640
[1] "Processing enrichment for level6"
[1] "Filtered term2gene table for level6 has 55986 rows"
[1] "First few rows of filtered term2gene:"
               Term           Gene
1                   LOC_Os11g37130
2 component *(OHP1) LOC_Os12g29570
3                   LOC_Os12g18640
[1] "Processing enrichment for level7"
[1] "Filtered term2gene table for level7 has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1      LOC_Os11g37130
2      LOC_Os12g29570
3      LOC_Os12g18640
[1] "Processing enrichment for level8"
[1] "Filtered term2gene table for level8 has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1      LOC_Os11g37130
2      LOC_Os12g29570
3      LOC_Os12g18640

No gene sets have size between 10 and 500 ...

--> return NULL...

[1] "Processing enrichment for protscriber"
[1] "Filtered term2gene table for protscriber has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1 <NA> LOC_Os11g37130
2 <NA> LOC_Os12g29570
3 <NA> LOC_Os12g18640

--> No gene can be mapped....

--> Expected input gene ID:

--> return NULL...

[1] "Processing enrichment for swissprot"
[1] "Filtered term2gene table for swissprot has 55986 rows"
[1] "First few rows of filtered term2gene:"
  Term           Gene
1      LOC_Os11g37130
2      LOC_Os12g29570
3      LOC_Os12g18640
[1] "All processing completed."

In [22]:
head(genelist)
head(term2gene$Gene)
datalist_deg

[1] "LOC_Os06g50880" "LOC_Os03g10780" "LOC_Os03g10460" "LOC_Os04g59480"
[5] "LOC_Os01g49026" "LOC_Os01g15860"

[1] "LOC_Os01g41710" "LOC_Os01g52240" "LOC_Os03g39610" "LOC_Os07g37550"
[5] "LOC_Os09g17740" "LOC_Os07g37240"

$deseq2_day4_filtered_results.csv
                      Gene         padj
1           LOC_Os06g50880 1.190073e-86
2           LOC_Os03g10780 2.744655e-66
3           LOC_Os03g10460 6.242776e-66
4           LOC_Os04g59480 3.865691e-65
5           LOC_Os01g49026 1.106510e-62
6           LOC_Os01g15860 1.151292e-61
7           LOC_Os12g35550 5.946809e-57
8           LOC_Os05g04370 2.948756e-52
9           LOC_Os04g32580 6.709604e-44
10          LOC_Os03g39860 1.884254e-43
11          LOC_Os06g39240 3.416868e-41
12          LOC_Os10g41550 3.758898e-40
13          LOC_Os12g06100 3.772197e-40
14          LOC_Os03g11660 9.764455e-40
15          LOC_Os02g41820 1.995428e-39
16          LOC_Os01g16430 1.388025e-38
17          LOC_Os07g37650 2.497044e-37
18          LOC_Os10g28320 3.367643e-37
19          LOC_Os04g49450 3.540967e-35
20          LOC_Os12g31790 5.675054e-35
21          LOC_Os09g31031 2.317540e-34
22          LOC_Os09g34970 8.694002e-34
23          LOC_Os08g03640 2.492431e-33
24          LOC_Os02g06480 2.928368e-33
25          LOC_Os03g19870 3.029397e-33
26          LOC_Os10g36680 1.258522e-32
27          LOC_Os05g48855 1.475450e-32
28          LOC_Os03g59480 2.490740e-32
29          LOC_Os04g57560 1.159479e-31
30          LOC_Os12g37720 6.166260e-31
31          LOC_Os02g38130 1.336602e-30
32          LOC_Os02g38050 3.621309e-30
33          LOC_Os10g31820 3.688183e-30
34          LOC_Os01g55170 5.190801e-30
35          LOC_Os01g08550 5.190801e-30
36          LOC_Os05g03490 5.485311e-30
37          LOC_Os07g37800 6.093185e-30
38          LOC_Os06g06330 8.163557e-30
39          LOC_Os07g46680 1.256074e-29
40          LOC_Os06g45360 2.552012e-29
41          LOC_Os12g33020 4.293236e-29
42          LOC_Os06g06470 4.293236e-29
43          LOC_Os04g40840 1.153905e-28
44          LOC_Os03g47550 1.057118e-27
45          LOC_Os07g13810 1.168698e-27
46          LOC_Os03g20470 1.447893e-27
47          LOC_Os01g68960 1.448078e-27
48          LOC_Os06g23530 1.668981e-27
49          LOC_Os12g08210 4.064147e-27
50          LOC_Os01g03090 8.755390e-27
51          LOC_Os10g41534 1.397635e-26
52          LOC_Os03g51840 3.088492e-26
53          LOC_Os06g04780 1.808323e-25
54          LOC_Os05g32370 2.061337e-25
55          LOC_Os01g64290 2.815664e-25
56          LOC_Os03g06220 4.109616e-25
57          LOC_Os10g34540 5.934747e-25
58          LOC_Os07g04550 1.099256e-24
59          LOC_Os08g25060 1.849879e-24
60          LOC_Os05g47490 1.867937e-24
61          LOC_Os02g47760 2.263808e-24
62          LOC_Os02g46956 2.699622e-24
63          LOC_Os08g25460 4.131014e-24
64          LOC_Os01g43390 5.013470e-24
65          LOC_Os04g48375 5.085599e-24
66          LOC_Os08g20570 7.961345e-24
67          LOC_Os01g53800 2.160710e-23
68          LOC_Os04g42040 2.561072e-23
69          LOC_Os01g63990 2.719469e-23
70          LOC_Os05g06300 3.356913e-23
71          LOC_Os03g08140 4.707954e-23
72          LOC_Os07g19060 5.560192e-23
73          LOC_Os02g20170 9.792414e-23
74          LOC_Os08g40919 1.254495e-22
75          LOC_Os03g58520 2.569881e-22
76          LOC_Os03g44430 4.247426e-22
77          LOC_Os10g36780 4.678300e-22
78          LOC_Os01g27530 5.855704e-22
79          LOC_Os05g32850 6.625477e-22
80          LOC_Os05g05440 7.159449e-22
81          LOC_Os07g42440 7.159449e-22
82          LOC_Os02g17870 1.671455e-21
83          LOC_Os10g32710 1.952475e-21
84          LOC_Os01g37790 3.030642e-21
85          LOC_Os05g01360 3.893187e-21
86          LOC_Os01g18100 3.928019e-21
87          LOC_Os10g35730 4.282975e-21
88          LOC_Os01g15010 6.164229e-21
89          LOC_Os03g42464 6.190469e-21
90          LOC_Os04g49660 1.025156e-20
91          LOC_Os10g29470 2.012334e-20
92          LOC_Os06g02028 2.012334e-20
93          LOC_Os05g01560 4.392376e-20
94          LOC_Os01g15900 4.392376e-20
95          LOC_Os06g42810 4.844292e-20
96          LOC_Os08g32540 5.282404e-20
97          LOC_Os08g16720 6.408670e-20
98          LOC_Os10g26620 1.144753e-19
99          LOC_Os01g69850 1.220946e-19
100         LOC_Os08g30820 1.381667e-19
101         LOC_Os08g02040 1.564647e-19
102         LOC_Os05g10625 1.579348e-19
103         LOC_Os12g03480 3.595044e-19
104         LOC_Os02g42374 4.093167e-19
105         LOC_Os03g01016 4.212991e-19
106         LOC_Os06g09280 4.948420e-19
107         LOC_Os10g24690 5.211472e-19
108         LOC_Os06g19444 5.445978e-19
109         LOC_Os11g16470 8.129307e-19
110         LOC_Os02g58090 9.853433e-19
111         LOC_Os03g20560 1.073800e-18
112         LOC_Os09g39980 1.143502e-18
113         LOC_Os02g17860 1.274499e-18
114         LOC_Os03g50070 1.380256e-18
115         LOC_Os04g50970 1.963918e-18
116         LOC_Os07g16140 2.024061e-18
117         LOC_Os07g38400 2.053223e-18
118         LOC_Os04g02310 2.063093e-18
119         LOC_Os01g03500 2.939901e-18
120         LOC_Os09g36240 3.750710e-18
121         LOC_Os09g20550 3.903159e-18
122         LOC_Os09g21040 4.168156e-18
123         LOC_Os12g34340 4.698519e-18
124         LOC_Os02g50200 5.697965e-18
125         LOC_Os03g17920 7.707270e-18
126         LOC_Os09g19750 7.774868e-18
127         LOC_Os08g43170 9.400450e-18
128         LOC_Os03g18620 1.436187e-17
129         LOC_Os04g42990 1.555790e-17
130         LOC_Os11g12650 1.564101e-17
131         LOC_Os01g02720 1.697918e-17
132         LOC_Os10g35570 1.758357e-17
133         LOC_Os01g45750 2.076114e-17
134         LOC_Os04g51454 2.186528e-17
135         LOC_Os01g04650 2.473555e-17
136         LOC_Os12g39440 2.486676e-17
137         LOC_Os02g35880 3.260869e-17
138         LOC_Os11g02180 3.372288e-17
139         LOC_Os04g40010 3.782692e-17
140         LOC_Os01g15890 3.782692e-17
141         LOC_Os01g62870 3.782692e-17
142         LOC_Os03g07180 3.782692e-17
143         LOC_Os02g44520 3.804335e-17
144         LOC_Os03g02970 4.983061e-17
145         LOC_Os12g17600 5.169231e-17
146         LOC_Os08g03360 5.410194e-17
147         LOC_Os04g52540 8.050882e-17
148         LOC_Os05g06660 9.994307e-17
149         LOC_Os08g02204 1.064885e-16
150         LOC_Os03g29240 1.186444e-16
151         LOC_Os07g22930 1.214381e-16
152         LOC_Os07g15880 1.360678e-16
153         LOC_Os01g32670 1.435263e-16
154         LOC_Os07g06740 1.437937e-16
155         LOC_Os12g44360 1.474894e-16
156         LOC_Os02g11060 1.629175e-16
157         LOC_Os05g04540 1.784318e-16
158         LOC_Os05g44570 1.829094e-16
159         LOC_Os05g14310 1.997320e-16
160         LOC_Os02g02750 2.002901e-16
161         LOC_Os04g40080 2.069375e-16
162         LOC_Os12g41390 2.069922e-16
163         LOC_Os07g43700 2.261783e-16
164         LOC_Os09g17580 2.361283e-16
165         LOC_Os01g27720 2.419746e-16
166         LOC_Os04g44924 2.422471e-16
167         LOC_Os01g22630 2.965086e-16
168         LOC_Os11g34460 3.366440e-16
169         LOC_Os07g42890 3.375030e-16
170         LOC_Os07g02910 4.263758e-16
171         LOC_Os06g21890 4.630176e-16
172         LOC_Os01g31890 4.700106e-16
173         LOC_Os10g32680 4.963289e-16
174         LOC_Os07g03270 6.617394e-16
175         LOC_Os01g39100 6.972351e-16
176         LOC_Os10g37980 7.626109e-16
177         LOC_Os01g43410 9.547516e-16
178         LOC_Os04g44790 1.440763e-15
179         LOC_Os02g13800 1.489322e-15
180         LOC_Os03g59060 1.524262e-15
181         LOC_Os09g30498 1.578410e-15
182         LOC_Os11g03300 1.618080e-15
183         LOC_Os04g56240 1.628771e-15
184         LOC_Os01g70520 1.709783e-15
185         LOC_Os01g53020 1.757746e-15
186         LOC_Os02g09460 1.895841e-15
187         LOC_Os07g42700 2.002124e-15
188         LOC_Os09g22440 2.074039e-15
189         LOC_Os05g08110 2.599655e-15
190         LOC_Os02g27790 2.599655e-15
191         LOC_Os02g03730 2.639196e-15
192         LOC_Os05g30250 2.989110e-15
193         LOC_Os01g04380 2.989110e-15
194         LOC_Os12g05050 3.316522e-15
195         LOC_Os12g39840 3.844800e-15
196         LOC_Os09g26570 3.844800e-15
197         LOC_Os03g60740 4.621133e-15
198         LOC_Os04g14760 5.277655e-15
199         LOC_Os11g10730 5.620848e-15
200         LOC_Os09g04800 6.158779e-15
201         LOC_Os03g22550 6.323872e-15
202         LOC_Os01g48680 6.433036e-15
203         LOC_Os10g01044 6.481037e-15
204         LOC_Os04g54350 6.489045e-15
205         LOC_Os01g63890 6.849107e-15
206         LOC_Os06g40940 6.849107e-15
207         LOC_Os01g68524 8.214358e-15
208         LOC_Os05g45130 8.526397e-15
209         LOC_Os07g49300 8.590247e-15
210         LOC_Os07g06130 1.397606e-14
211         LOC_Os10g01060 1.407816e-14
212         LOC_Os05g35190 1.521340e-14
213         LOC_Os08g32660 1.592218e-14
214         LOC_Os05g49230 1.592218e-14
215         LOC_Os07g49390 1.617602e-14
216         LOC_Os09g34850 1.632780e-14
217         LOC_Os02g03670 1.811053e-14
218         LOC_Os07g29200 1.811053e-14
219         LOC_Os03g18400 1.902595e-14
220         LOC_Os11g10740 1.902595e-14
221         LOC_Os03g57490 2.000261e-14
222         LOC_Os07g29410 2.000261e-14
223         LOC_Os01g66350 2.003513e-14
224         LOC_Os11g03900 2.522206e-14
225         LOC_Os01g29230 2.613591e-14
226         LOC_Os08g42760 2.695949e-14
227         LOC_Os04g55800 2.758007e-14
228         LOC_Os05g16670 2.778659e-14
229         LOC_Os03g18870 2.981416e-14
230         LOC_Os02g06890 3.578181e-14
231         LOC_Os08g09180 4.082121e-14
232         LOC_Os12g35320 4.249705e-14
233         LOC_Os09g10780 4.373014e-14
234         LOC_Os12g03720 4.504814e-14
235         LOC_Os05g31750 5.261094e-14
236         LOC_Os01g16220 5.648118e-14
237         LOC_Os03g28100 5.934437e-14
238         LOC_Os05g32860 7.093510e-14
239         LOC_Os09g35970 7.398698e-14
240         LOC_Os06g36940 7.725999e-14
241         LOC_Os02g45344 8.043194e-14
242         LOC_Os10g10870 8.116060e-14
243         LOC_Os07g44660 8.788187e-14
244         LOC_Os03g51380 8.985750e-14
245         LOC_Os02g53790 9.469117e-14
246         LOC_Os05g02060 9.645852e-14
247         LOC_Os01g25386 1.090861e-13
248         LOC_Os03g39830 1.333788e-13
249         LOC_Os01g59560 1.532335e-13
250         LOC_Os12g40920 1.606695e-13
251         LOC_Os05g37660 1.616842e-13
252         LOC_Os02g12900 1.631954e-13
253         LOC_Os04g56400 1.946187e-13
254         LOC_Os11g06230 2.151159e-13
255         LOC_Os01g57360 2.424746e-13
256         LOC_Os04g55560 2.753456e-13
257         LOC_Os07g43170 2.820370e-13
258         LOC_Os05g38830 2.820370e-13
259         LOC_Os06g17880 2.820370e-13
260         LOC_Os04g05880 3.018846e-13
261         LOC_Os02g06470 3.117080e-13
262         LOC_Os03g59460 3.395191e-13
263         LOC_Os08g05470 3.429407e-13
264         LOC_Os06g23350 3.486408e-13
265         LOC_Os11g04700 3.489054e-13
266         LOC_Os09g24710 4.715033e-13
267         LOC_Os10g35630 4.951613e-13
268         LOC_Os04g54790 4.951613e-13
269         LOC_Os01g07280 5.286456e-13
270         LOC_Os10g02270 5.304607e-13
271         LOC_Os08g40190 5.304607e-13
272         LOC_Os09g21450 5.323177e-13
273         LOC_Os07g36500 5.383533e-13
274         LOC_Os05g31670 5.798324e-13
275         LOC_Os05g08980 6.501597e-13
276         LOC_Os03g43524 6.602801e-13
277         LOC_Os02g54640 7.094142e-13
278         LOC_Os08g41830 7.922546e-13
279         LOC_Os05g05680 8.679475e-13
280         LOC_Os06g45840 8.945964e-13
281         LOC_Os03g59774 9.062788e-13
282         LOC_Os11g32890 9.261956e-13
283         LOC_Os02g13560 1.038282e-12
284         LOC_Os03g14050 1.105096e-12
285         LOC_Os01g68020 1.144924e-12
286         LOC_Os02g43930 1.170565e-12
287         LOC_Os02g09670 1.216366e-12
288         LOC_Os12g29400 1.271942e-12
289         LOC_Os08g04840 1.280857e-12
290         LOC_Os03g58920 1.384946e-12
291         LOC_Os02g43194 1.447177e-12
292         LOC_Os02g35690 1.470716e-12
293         LOC_Os03g36080 1.592106e-12
294         LOC_Os03g03100 1.688488e-12
295         LOC_Os05g37170 1.688488e-12
296         LOC_Os11g42030 1.774663e-12
297         LOC_Os12g16524 1.795213e-12
298         LOC_Os10g21360 1.952718e-12
299         LOC_Os09g25945 2.274449e-12
300         LOC_Os06g14324 2.425165e-12
301         LOC_Os06g02210 2.479096e-12
302         LOC_Os07g49400 2.549803e-12
303         LOC_Os09g22500 2.549803e-12
304         LOC_Os06g36400 2.553286e-12
305         LOC_Os06g13720 2.587389e-12
306         LOC_Os01g20880 2.605890e-12
307         LOC_Os10g38710 2.642947e-12
308         LOC_Os07g02192 2.981335e-12
309         LOC_Os06g24070 2.981491e-12
310         LOC_Os07g46470 3.061167e-12
311         LOC_Os08g33380 3.484267e-12
312         LOC_Os07g47500 3.759733e-12
313         LOC_Os08g11470 3.788816e-12
314         LOC_Os07g48780 4.143783e-12
315         LOC_Os08g14440 4.150171e-12
316         LOC_Os12g33150 4.157097e-12
317         LOC_Os04g56230 4.206744e-12
318         LOC_Os12g39380 4.226838e-12
319         LOC_Os03g11910 4.226838e-12
320         LOC_Os02g43330 4.644692e-12
321         LOC_Os02g49680 4.777258e-12
322         LOC_Os06g05359 5.184516e-12
323         LOC_Os01g13024 5.275732e-12
324         LOC_Os01g40580 5.304460e-12
325         LOC_Os03g57120 5.783759e-12
326         LOC_Os10g35000 6.249915e-12
327         LOC_Os05g14270 6.448528e-12
328         LOC_Os12g35080 6.889037e-12
329         LOC_Os01g66980 7.079602e-12
330         LOC_Os10g12290 7.500683e-12
331         LOC_Os01g07700 7.673225e-12
332         LOC_Os12g25180 8.105578e-12
333         LOC_Os02g38160 8.105578e-12
334         LOC_Os11g04850 8.105578e-12
335         LOC_Os05g06399 8.224791e-12
336         LOC_Os04g35910 8.243771e-12
337         LOC_Os08g38820 8.327703e-12
338         LOC_Os11g04560 8.414919e-12
339         LOC_Os08g37874 8.605148e-12
340         LOC_Os08g33820 8.649507e-12
341         LOC_Os05g51754 8.668535e-12
342         LOC_Os08g22149 8.758348e-12
343         LOC_Os05g50340 9.402019e-12
344         LOC_Os09g34214 9.668173e-12
345         LOC_Os02g56440 9.923923e-12
346         LOC_Os07g13634 1.013554e-11
347         LOC_Os03g64020 1.016695e-11
348         LOC_Os05g02230 1.049216e-11
349         LOC_Os03g53220 1.116937e-11
350         LOC_Os05g47540 1.127366e-11
351         LOC_Os06g48240 1.147782e-11
352         LOC_Os01g45530 1.195245e-11
353         LOC_Os02g49230 1.207605e-11
354         LOC_Os02g12410 1.211393e-11
355         LOC_Os02g53680 1.218150e-11
356         LOC_Os05g12300 1.250500e-11
357         LOC_Os07g04990 1.349760e-11
358         LOC_Os08g34130 1.434108e-11
359         LOC_Os09g13940 1.437763e-11
360         LOC_Os01g73890 1.467661e-11
361         LOC_Os03g07930 1.473305e-11
362         LOC_Os05g06480 1.482276e-11
363         LOC_Os05g50640 1.484452e-11
364         LOC_Os02g48560 1.581053e-11
365         LOC_Os06g19750 1.596114e-11
366         LOC_Os10g35960 1.611828e-11
367         LOC_Os07g38790 1.673077e-11
368         LOC_Os11g37970 1.673077e-11
369         LOC_Os04g12720 1.799187e-11
370         LOC_Os05g31760 1.824956e-11
371         LOC_Os06g48560 1.854515e-11
372         LOC_Os07g44430 2.029887e-11
373         LOC_Os04g59610 2.055058e-11
374         LOC_Os04g40720 2.146986e-11
375         LOC_Os01g02400 2.163618e-11
376         LOC_Os12g04360 2.169338e-11
377         LOC_Os06g04190 2.188208e-11
378         LOC_Os04g40300 2.188247e-11
379         LOC_Os11g47970 2.228619e-11
380         LOC_Os02g10120 2.286670e-11
381         LOC_Os06g45140 2.320002e-11
382         LOC_Os05g48390 2.440622e-11
383         LOC_Os04g44430 2.821900e-11
384         LOC_Os02g43070 2.821900e-11
385         LOC_Os12g03040 2.849447e-11
386         LOC_Os11g03580 3.132287e-11
387         LOC_Os09g39910 3.240117e-11
388         LOC_Os08g06220 3.240117e-11
389         LOC_Os01g74650 3.333871e-11
390         LOC_Os02g26404 3.625612e-11
391         LOC_Os04g20180 3.634600e-11
392         LOC_Os03g13550 3.730113e-11
393         LOC_Os05g10620 3.975181e-11
394         LOC_Os06g08140 4.014901e-11
395         LOC_Os09g33930 4.015806e-11
396         LOC_Os03g04450 4.100428e-11
397         LOC_Os09g35030 4.150901e-11
398         LOC_Os08g20580 4.215529e-11
399         LOC_Os10g42780 4.229931e-11
400         LOC_Os12g35070 4.229931e-11
401         LOC_Os03g44530 4.229931e-11
402         LOC_Os08g08140 4.229931e-11
403         LOC_Os03g53660 4.430556e-11
404         LOC_Os09g33530 4.636109e-11
405         LOC_Os07g38630 4.997354e-11
406         LOC_Os01g44390 5.437211e-11
407         LOC_Os02g46390 5.718553e-11
408         LOC_Os12g06550 5.773435e-11
409         LOC_Os07g49110 6.000365e-11
410         LOC_Os01g39790 6.167548e-11
411         LOC_Os01g08290 6.972447e-11
412         LOC_Os01g22980 7.081425e-11
413         LOC_Os02g56910 7.235587e-11
414         LOC_Os03g20680 7.638805e-11
415         LOC_Os02g53130 7.976942e-11
416         LOC_Os05g38680 8.607848e-11
417         LOC_Os02g06350 8.863955e-11
418         LOC_Os03g22780 8.913517e-11
419         LOC_Os09g13890 9.223716e-11
420         LOC_Os06g11500 9.307521e-11
421         LOC_Os03g44300 9.438723e-11
422         LOC_Os02g20040 9.503409e-11
423         LOC_Os01g29469 9.642931e-11
424         LOC_Os07g07890 9.800206e-11
425         LOC_Os03g29950 1.026517e-10
426         LOC_Os01g57004 1.030256e-10
427         LOC_Os06g43810 1.055490e-10
428         LOC_Os01g39060 1.096277e-10
429         LOC_Os01g09300 1.110357e-10
430         LOC_Os05g44340 1.172470e-10
431         LOC_Os05g04890 1.298111e-10
432         LOC_Os08g06550 1.337371e-10
433         LOC_Os01g43040 1.386632e-10
434         LOC_Os09g17329 1.403122e-10
435         LOC_Os03g63910 1.454552e-10
436         LOC_Os03g10180 1.499588e-10
437         LOC_Os08g14880 1.573823e-10
438         LOC_Os09g23540 1.719908e-10
439         LOC_Os12g02660 1.745573e-10
440         LOC_Os04g58620 1.745573e-10
441         LOC_Os01g50849 1.761873e-10
442         LOC_Os06g04210 1.788234e-10
443         LOC_Os12g01449 1.792617e-10
444         LOC_Os04g02620 1.890332e-10
445         LOC_Os07g08300 2.014768e-10
446         LOC_Os08g37930 2.069908e-10
447         LOC_Os08g38140 2.089087e-10
448         LOC_Os11g20020 2.108966e-10
449         LOC_Os06g49750 2.152149e-10
450         LOC_Os07g01930 2.286173e-10
451         LOC_Os01g68680 2.286173e-10
452         LOC_Os01g06660 2.318710e-10
453         LOC_Os08g27650 2.322357e-10
454         LOC_Os06g39690 2.360673e-10
455         LOC_Os07g07480 2.394431e-10
456         LOC_Os02g57100 2.574098e-10
457         LOC_Os05g33900 2.597158e-10
458         LOC_Os09g37620 2.621470e-10
459         LOC_Os07g43560 2.721250e-10
460         LOC_Os04g21820 2.721420e-10
461         LOC_Os03g20700 2.830605e-10
462         LOC_Os09g11460 2.844290e-10
463         LOC_Os04g42520 2.926515e-10
464         LOC_Os06g39344 2.937016e-10
465         LOC_Os02g34960 3.052000e-10
466         LOC_Os12g05210 3.112197e-10
467         LOC_Os01g44430 3.163812e-10
468         LOC_Os03g32170 3.223610e-10
469         LOC_Os07g18110 3.302710e-10
470         LOC_Os01g40080 3.362176e-10
471         LOC_Os02g38240 3.461752e-10
472         LOC_Os01g43080 3.461752e-10
473         LOC_Os03g50280 3.487476e-10
474         LOC_Os02g18870 3.560965e-10
475         LOC_Os09g25610 3.563716e-10
476         LOC_Os12g03350 3.586381e-10
477         LOC_Os01g15990 3.621838e-10
478         LOC_Os01g55570 3.649235e-10
479         LOC_Os12g14550 3.785849e-10
480         LOC_Os01g71720 3.815287e-10
481         LOC_Os04g51800 3.857005e-10
482         LOC_Os03g23980 3.881054e-10
483         LOC_Os09g09650 3.895295e-10
484         LOC_Os11g07980 3.910821e-10
485         LOC_Os06g28194 3.926703e-10
486         LOC_Os05g38350 3.972535e-10
487         LOC_Os03g56370 4.191929e-10
488         LOC_Os02g45870 4.240723e-10
489         LOC_Os04g38410 4.284396e-10
490         LOC_Os12g04500 4.624796e-10
491         LOC_Os07g47090 4.891925e-10
492         LOC_Os09g27420 4.934086e-10
493         LOC_Os09g31502 4.949628e-10
494         LOC_Os06g21590 4.969760e-10
495         LOC_Os11g29720 5.031223e-10
496         LOC_Os11g04720 5.204259e-10
497         LOC_Os09g17600 5.205795e-10
498         LOC_Os08g36480 5.323784e-10

In [23]:
deg_df

     Gene           padj
1    LOC_Os06g50880 1.190073e-86
2    LOC_Os03g10780 2.744655e-66
3    LOC_Os03g10460 6.242776e-66
4    LOC_Os04g59480 3.865691e-65
5    LOC_Os01g49026 1.106510e-62
6    LOC_Os01g15860 1.151292e-61
7    LOC_Os12g35550 5.946809e-57
8    LOC_Os05g04370 2.948756e-52
9    LOC_Os04g32580 6.709604e-44
10   LOC_Os03g39860 1.884254e-43
11   LOC_Os06g39240 3.416868e-41
12   LOC_Os10g41550 3.758898e-40
13   LOC_Os12g06100 3.772197e-40
14   LOC_Os03g11660 9.764455e-40
15   LOC_Os02g41820 1.995428e-39
16   LOC_Os01g16430 1.388025e-38
17   LOC_Os07g37650 2.497044e-37
18   LOC_Os10g28320 3.367643e-37
19   LOC_Os04g49450 3.540967e-35
20   LOC_Os12g31790 5.675054e-35
21   LOC_Os09g31031 2.317540e-34
22   LOC_Os09g34970 8.694002e-34
23   LOC_Os08g03640 2.492431e-33
24   LOC_Os02g06480 2.928368e-33
25   LOC_Os03g19870 3.029397e-33
26   LOC_Os10g36680 1.258522e-32
27   LOC_Os05g48855 1.475450e-32
28   LOC_Os03g59480 2.490740e-32
29   LOC_Os04g57560 1.159479e-31
30   LOC_Os12g37720 6.166260e-31
⋮    ⋮              ⋮
6128 LOC_Os02g06910 0.04897941
6129 LOC_Os10g17930 0.04904349
6130 LOC_Os12g31860 0.04904886
6131 LOC_Os07g32710 0.04908903
6132 LOC_Os10g39030 0.04913290
6133 LOC_Os07g35280 0.04914512
6134 LOC_Os01g18744 0.04914512
6135 LOC_Os03g12020 0.04914582
6136 LOC_Os01g50000 0.04915982
6137 LOC_Os01g24750 0.04922141
6138 LOC_Os04g43200 0.04923117
6139 LOC_Os09g36350 0.04926256
6140 LOC_Os01g51010 0.04933493
6141 LOC_Os08g38490 0.04939862
6142 LOC_Os03g44630 0.04939862
6143 LOC_Os02g02320 0.04941706
6144 LOC_Os11g30910 0.04956911
6145 LOC_Os02g40730 0.04958713
6146 LOC_Os05g46720 0.04960679
6147 LOC_Os12g39820 0.04963593
6148 LOC_Os01g55010 0.04963608
6149 LOC_Os12g43880 0.04965836
6150 LOC_Os12g08130 0.04971204
6151 LOC_Os05g39150 0.04971694
6152 LOC_Os05g25640 0.04981540
6153 LOC_Os12g10710 0.04985130
6154 LOC_Os01g45360 0.04988568
6155 LOC_Os03g32100 0.04992892
6156 LOC_Os10g41860 0.04998280
6157 LOC_Os08g27250 0.04998973

Use the following code to separate out the upregulated and down regulated genes. 

```

    # Separate upregulated and downregulated genes
    upregulated_genes <- deg_df %>%
                         filter(log2FoldChange > 1)
    downregulated_genes <- deg_df %>%
                           filter(log2FoldChange < -1)
```

---


```
        enrich <- enricher(
                    gene = upregulated_genes,
                    pvalueCutoff = 0.1,
                    pAdjustMethod = "BH",
                    minGSSize = 10,
                    maxGSSize = 500,
                    qvalueCutoff = 0.2,
                    TERM2GENE = tempset)
```
```
        enrich <- enricher(
                    gene = downregulated_genes,
                    pvalueCutoff = 0.1,
                    pAdjustMethod = "BH",
                    minGSSize = 10,
                    maxGSSize = 500,
                    qvalueCutoff = 0.2,
                    TERM2GENE = tempset)
```